// Structured Traps & Snares reference data — same pattern as
// firstAidData.ts/shelterData.ts/findingWaterData.ts. 100 primitive trap,
// live-capture, and aquatic-trap designs, framed throughout the source
// material as demonstration/practice models rather than deployable lethal
// devices — see the page's own disclaimer. Wildlife trapping is heavily
// regulated by species, jurisdiction, and season; nothing here implies a
// given design is legal to actually deploy.

export interface TrapNote {
  label: string
  text: string
}

export interface TrapDesign {
  num: number
  name: string
  type: string
  difficulty: number
  /** Leading purpose/context line some entries have before their materials
   * list (e.g. "Best suited to: ..."), verbatim from the source. */
  intro?: string
  materials: string
  construction: string[]
  notes: TrapNote[]
}

export interface TrapCategory {
  key: string
  title: string
  emoji: string
  designs: TrapDesign[]
}

export const TRAP_CATEGORIES: TrapCategory[] = [
  {
    key: 'primitive',
    title: 'Primitive Trap & Capture Designs',
    emoji: '🪤',
    designs: [
      {
        num: 1,
        name: 'Paiute-Style Deadfall — Practice Version',
        type: 'Trigger mechanism',
        difficulty: 2,
        materials: '3 straight sticks, cordage, a lightweight training weight',
        construction: [
          'Find a sturdy stick approximately the length of your forearm. This is the upright support.',
          'Find a second straight stick to act as the trigger lever.',
          'Find a third stick to act as the diagonal support.',
          'Stand the upright against the training weight.',
          'Arrange the lever against the upright so that it can support the weight.',
          'Position the diagonal stick between the lever and the ground.',
          'Tie or arrange the cordage so that pulling the trigger point disrupts the arrangement.',
          'Put a lightweight practice object on the system.',
          'Test it repeatedly from the side rather than placing any part of your body underneath it.',
        ],
        notes: [
          { label: 'Principle', text: 'Three pieces of wood create a friction-dependent mechanical trigger. A small movement at the trigger point releases the supported load.' },
          { label: 'Practice tip', text: 'Start with a small stick bundle rather than a heavy rock or log.' },
        ],
      },
      {
        num: 2,
        name: 'Figure-Four Trigger',
        type: 'Primitive trigger',
        difficulty: 2,
        intro: "The figure-four is another useful mechanism to learn because it teaches how three interlocking pieces can support a load until one is displaced.",
        materials: '3 straight sticks, cordage, lightweight training weight',
        construction: [
          'Prepare a vertical support stick.',
          'Prepare a horizontal trigger stick.',
          'Prepare a diagonal stick.',
          'Arrange the three pieces so they form the characteristic 4-shaped profile when viewed from the side.',
          'Place your training load on the horizontal member.',
          'Put the bait substitute or trigger marker at the point where the horizontal and diagonal members meet.',
          'Gently test the trigger with a small load.',
          'Adjust the contact points until the mechanism releases consistently.',
        ],
        notes: [
          { label: 'Key lesson', text: "The important part isn't the exact shape — it's creating a stable structure whose balance depends on a deliberately small trigger movement." },
        ],
      },
      {
        num: 3,
        name: 'Figure-Four Variation',
        type: 'Primitive trigger',
        difficulty: 2,
        intro: 'This variation uses the same basic principle but changes the geometry.',
        materials: '3 sticks, cordage, practice weight',
        construction: [
          'Use a relatively thick stick as the main support.',
          'Place a shorter horizontal member against it.',
          'Use a third stick diagonally between the horizontal member and the ground.',
          'Create a small contact point between the three components.',
          'Place the training weight on the supported member.',
          'Apply a small sideways force to the trigger.',
          "If it doesn't release, change the angle of the diagonal stick.",
          'Continue until you can reliably predict when the mechanism will release.',
        ],
        notes: [
          { label: 'Why practice this one?', text: 'It teaches an important survival skill: building mechanical systems from irregular natural materials rather than manufactured parts.' },
        ],
      },
      {
        num: 4,
        name: 'Split-Stick Deadfall Mechanism',
        type: 'Primitive mechanical trap',
        difficulty: 2,
        intro: 'For handbook purposes, use this as a non-deployable demonstration model.',
        materials: 'One split stick, two support sticks, cordage, lightweight object',
        construction: [
          'Find a straight branch and split it lengthwise.',
          'Use one half as a support.',
          'Place a second stick across the support.',
          'Use the other half of the split branch as a trigger.',
          'Arrange the pieces so the trigger holds the practice weight.',
          'Touch the trigger with another stick.',
          'Observe how the pressure transfers through the structure.',
          'Experiment with different angles.',
        ],
        notes: [
          { label: 'Failure points', text: 'Wet wood can become slippery. Rounded sticks provide poor contact. Excessive weight can cause unpredictable failure.' },
        ],
      },
      {
        num: 5,
        name: 'Toggle Deadfall Mechanism',
        type: 'Primitive trigger',
        difficulty: 3,
        materials: 'Straight stick, small toggle, cordage, practice load',
        construction: [
          'Attach cordage to the practice load.',
          'Route the cord around a support.',
          'Place a small toggle across the cord.',
          'Position the toggle so it bears against the support.',
          'Pull the cord gently until the toggle carries the load.',
          'Touch or move the trigger end.',
          'The toggle should rotate out of position.',
          'Repeat with progressively smaller trigger movements.',
        ],
        notes: [
          { label: 'Skill learned', text: 'Mechanical advantage and rotational release.' },
        ],
      },
      {
        num: 6,
        name: 'Lean-To Deadfall — Practice Model',
        type: 'Primitive structure',
        difficulty: 2,
        intro: 'Instead of constructing a functional animal-killing device, use a cardboard box, foam block, or very light wooden frame as the falling object.',
        materials: 'Lightweight falling object, small support stick, cordage',
        construction: [
          'Find a flat area.',
          'Prop the lightweight object at an angle.',
          'Use a small stick as the support.',
          'Attach a cord to the support.',
          'Route the cord to a remote trigger point.',
          'Pull the cord from several feet away.',
          'Observe how the support collapses.',
        ],
        notes: [
          { label: "Why it's useful", text: 'This demonstrates the basic concept behind many primitive deadfall arrangements without creating an unattended lethal trap.' },
        ],
      },
      {
        num: 7,
        name: 'Counterweight Mechanism',
        type: 'Mechanical trap principle',
        difficulty: 3,
        intro: 'This is a particularly useful concept for a survival handbook because it teaches balance rather than simply relying on friction.',
        materials: 'Branch or pole, cordage, lightweight counterweight, training object',
        construction: [
          'Lay the pole across a stable support.',
          'Attach cordage to one end.',
          'Hang the counterweight from the opposite side.',
          'Adjust the position of the pivot.',
          'Experiment with different counterweight positions.',
          'Find the point where a small movement produces a large change in balance.',
          'Add a simple trigger to hold the system.',
          'Test it with a lightweight load.',
        ],
        notes: [
          { label: 'Principle', text: 'Moving the pivot changes the mechanical advantage.' },
        ],
      },
      {
        num: 8,
        name: 'Spring-Pole Demonstration',
        type: 'Spring mechanism',
        difficulty: 3,
        intro: 'This is best practiced with a dummy target, not an animal.',
        materials: 'Flexible sapling or pole, cordage, trigger stick, lightweight object',
        construction: [
          'Select a flexible pole that naturally bends without cracking.',
          'Bend it carefully and determine its safe range.',
          'Secure it temporarily with cordage.',
          'Attach a line from the bent pole to a trigger.',
          'Set the trigger so it holds the pole under tension.',
          'Place a lightweight dummy target nearby.',
          'Release the trigger from a safe position.',
          'Inspect the system for broken wood or cordage.',
        ],
        notes: [
          { label: 'Safety', text: 'Never position yourself inside the movement path of the spring pole.' },
        ],
      },
      {
        num: 9,
        name: 'Stone/Log Enclosure',
        type: 'Live-capture enclosure concept',
        difficulty: 2,
        intro: 'Rather than making a falling-weight trap, construct a funnel-shaped enclosure that demonstrates how animals can be guided toward a confined area.',
        materials: 'Branches, stones, cordage if necessary',
        construction: [
          'Choose a location with obvious animal movement.',
          'Arrange branches or stones into two converging sides.',
          'Leave a relatively wide entrance.',
          'Gradually narrow the passage.',
          'Finish at a small enclosure.',
          'Keep the enclosure open rather than using a crushing mechanism.',
          'If practicing animal capture, use a purpose-built live-capture cage rather than an improvised enclosure.',
        ],
        notes: [
          { label: 'Principle', text: 'Animals naturally follow the path of least resistance. Funnels exploit movement behavior rather than force.' },
        ],
      },
      {
        num: 10,
        name: 'Primitive Box Live-Capture Trap',
        type: 'Live capture',
        difficulty: 3,
        intro: 'Best suited to: appropriate small animals only where legal. A purpose-built cage/box trap is considerably preferable to an improvised lethal device.',
        materials: 'Wooden box or sturdy wire-mesh cage, hinged or sliding door, trigger stick/treadle, cordage or wire, suitable bait',
        construction: [
          "Build a sturdy enclosure large enough that the intended animal isn't crushed or trapped against the walls.",
          'Make one end into a door.',
          'The door should close without injuring the animal.',
          'Install a treadle or trigger toward the rear.',
          'Connect the treadle to the door mechanism.',
          'Put the bait beyond the trigger.',
          'Test the door with a stick rather than your fingers.',
          'Verify that the animal cannot injure itself on sharp edges.',
          'Place the trap only where the species and method are legally permitted.',
          'Check it according to the applicable regulations.',
        ],
        notes: [
          { label: 'Important', text: "Live-capture traps aren't automatically legal simply because they're non-lethal. Wildlife agencies regulate trapping methods, and requirements can include licensing, approved trap types, placement rules, and inspection intervals." },
        ],
      },
      {
        num: 11,
        name: 'Platform Deadfall — Practice Model',
        type: 'Primitive trigger/mechanical exercise',
        difficulty: 2,
        intro: 'Purpose: learn how a trigger can support a suspended or elevated load.',
        materials: '3–4 straight sticks, cordage, small lightweight training weight, small piece of cardboard or wood for the platform',
        construction: [
          'Make a small platform from two parallel sticks.',
          'Place the lightweight training object on the platform.',
          'Build a simple three-stick support underneath one side.',
          'Attach cordage to the support.',
          'Arrange the trigger so pulling the cord causes the support to collapse.',
          'Test the mechanism using only the lightweight object.',
          'Adjust the contact points until the trigger releases predictably.',
          'Practice resetting it without putting your hands beneath the load.',
        ],
        notes: [
          { label: 'Principle', text: 'The platform distributes weight while the trigger controls when the supporting structure loses stability.' },
        ],
      },
      {
        num: 12,
        name: 'Baited Trigger Mechanism',
        type: 'Trigger-system exercise',
        difficulty: 2,
        intro: 'This demonstrates how bait can be incorporated into a mechanical trigger without building a lethal trap.',
        materials: 'Small box or cardboard enclosure, stick trigger, cordage, bait substitute',
        construction: [
          'Place the bait substitute at the back of the enclosure.',
          'Run a small stick or treadle across the entrance path.',
          'Connect the treadle to a lightweight door or flap.',
          'Arrange the mechanism so disturbing the treadle moves the door.',
          'Test it using a stick or small object.',
          'Adjust the trigger sensitivity.',
          'Make sure nothing sharp or crushing is involved.',
        ],
        notes: [
          { label: 'Survival lesson', text: 'Bait placement and trigger sensitivity are often more important than complexity.' },
        ],
      },
      {
        num: 13,
        name: 'Trail-Triggered Enclosure',
        type: 'Live-capture concept',
        difficulty: 2,
        intro: 'Purpose: guide an animal toward a harmless containment area.',
        materials: 'Sticks, brush, rope/cordage, small live-capture cage or open training enclosure',
        construction: [
          'Identify a naturally occurring animal pathway.',
          "Don't block the entire path.",
          'Arrange branches on either side to create a gradual funnel.',
          'Leave enough room for the intended animal to move normally.',
          'Direct the funnel toward the entrance of a live-capture enclosure.',
          'Keep the enclosure free of sharp edges.',
          'Test the arrangement yourself by following the pathway.',
          'Remove it immediately if non-target animals could become trapped.',
        ],
        notes: [
          { label: 'Key principle', text: 'Guide rather than force.' },
        ],
      },
      {
        num: 14,
        name: 'Burrow-Entrance Live-Capture Box',
        type: 'Live capture',
        difficulty: 3,
        materials: 'Small wooden or wire-mesh cage, sliding/hinged door, treadle, cordage or suitable hardware, appropriate bait',
        construction: [
          'Use a cage large enough for the intended species.',
          'Position the entrance near — but not inside — the burrow.',
          'Install the door so it closes without crushing.',
          'Put the treadle several inches behind the entrance.',
          'Connect the treadle to the door.',
          'Place bait beyond the treadle.',
          'Test the mechanism using a stick.',
          'Ensure the door cannot accidentally lock a non-target animal inside.',
          'Check the trap according to applicable regulations.',
        ],
        notes: [
          { label: 'Important', text: 'Never simply seal an occupied burrow or dig into one to force an animal into a trap.' },
        ],
      },
      {
        num: 15,
        name: 'Funnel-Entrance Live Trap',
        type: 'Live capture',
        difficulty: 2,
        materials: 'Wire mesh, woven sticks, or a commercially manufactured cage, cordage, bait',
        construction: [
          'Construct a cage with an opening at one end.',
          'Build a funnel-shaped entrance whose wide end faces outward.',
          'Make the interior opening large enough for the intended animal.',
          'Smooth or cover sharp wire ends.',
          'Place bait toward the rear.',
          'Position the cage along an appropriate travel route.',
          'Test that the animal can enter without becoming injured.',
          "Make sure the funnel doesn't function as a crushing or strangling mechanism.",
        ],
        notes: [
          { label: 'Advantage', text: 'A funnel can make the entrance obvious while making it difficult for an animal to immediately find its way back out.' },
        ],
      },
      {
        num: 16,
        name: 'Two-Door Box Trap',
        type: 'Live capture',
        difficulty: 3,
        materials: 'Wooden or wire-mesh box, two lightweight doors, two hinges/sliding tracks, treadle, cordage/hardware',
        construction: [
          'Build a rectangular enclosure.',
          'Put a door at each end.',
          'Make both doors swing or slide freely.',
          'Install the treadle approximately in the middle.',
          'Connect the treadle to the door mechanism.',
          'Place bait beyond the treadle.',
          'Test the trap with a stick.',
          'Confirm both doors close without slamming onto an animal.',
          'Check the enclosure frequently when legally deployed.',
        ],
        notes: [
          { label: 'Why two doors?', text: 'An animal entering from either direction can encounter the same containment mechanism, making the design useful along established travel routes.' },
        ],
      },
      {
        num: 17,
        name: 'Sliding-Door Box Trap',
        type: 'Live capture',
        difficulty: 3,
        materials: 'Wooden box, sliding door, two guide rails, treadle, cordage',
        construction: [
          'Build a box with an opening at one end.',
          'Install two parallel guides around the opening.',
          'Make a lightweight door that can move vertically or horizontally in those guides.',
          'Attach the door to the trigger mechanism.',
          'Place the treadle inside.',
          'Put bait beyond the treadle.',
          'Test the door repeatedly.',
          'Ensure the door cannot fall with enough force to injure the animal.',
          'Make sure the animal has adequate ventilation.',
        ],
        notes: [
          { label: 'Failure points', text: 'Door binding. Wet wood swelling. Cordage slipping. Trigger requiring too much force.' },
        ],
      },
      {
        num: 18,
        name: 'Gravity-Door Live Trap',
        type: 'Live capture',
        difficulty: 2,
        materials: 'Cage or wooden box, lightweight door, guide rails, treadle or trigger',
        construction: [
          'Build a vertical entrance.',
          'Install guide rails on either side.',
          'Place a lightweight door in the rails.',
          'Raise the door and hold it with the trigger.',
          'Position the treadle behind the entrance.',
          'Connect the treadle to the door.',
          'Test with a stick.',
          "Ensure the door closes gently and cannot trap an animal's limbs.",
        ],
        notes: [
          { label: 'Advantages', text: 'Few moving components. Can be constructed from simple materials. Easy to reset.' },
        ],
      },
      {
        num: 19,
        name: 'Treadle-Door Box Trap',
        type: 'Live capture',
        difficulty: 3,
        intro: 'This is one of the most useful mechanisms to understand for a survival handbook.',
        materials: 'Box/cage, door, treadle board, cordage, suitable bait',
        construction: [
          'Build the enclosure.',
          'Install a freely moving door.',
          'Place a small board across the floor as the treadle.',
          'Connect the treadle to the door.',
          'Put the bait beyond the treadle.',
          'The animal enters to reach the bait.',
          'Its weight depresses the treadle.',
          'The door closes.',
          'Test the complete system several times with a stick.',
          'Verify that the captured animal cannot injure itself.',
        ],
        notes: [
          { label: 'Important', text: 'A live-capture trap should never be considered "set and forget." Applicable wildlife regulations may specify inspection intervals.' },
        ],
      },
      {
        num: 20,
        name: 'Basket Cage Trap',
        type: 'Primitive/live capture',
        difficulty: 3,
        materials: 'Flexible branches, cordage, stronger sticks for a frame, bait',
        construction: [
          'Make a circular or rectangular frame from sturdy sticks.',
          'Weave flexible branches around the frame.',
          'Leave one entrance.',
          'Construct the entrance as a funnel.',
          'Secure all sharp or broken ends.',
          'Put bait toward the rear.',
          'Reinforce weak sections with cordage.',
          'Test the structure for collapse.',
          'If used for wildlife, make sure the cage is appropriate for the species and legally permitted.',
          'Check it frequently and release non-target animals promptly.',
        ],
        notes: [],
      },
      {
        num: 21,
        name: 'Bottle-Style Small-Animal Trap',
        type: 'Live capture',
        difficulty: 2,
        intro: 'Best for: demonstrating containment principles with small animals; suitability depends on species and local law.',
        materials: 'Sturdy plastic bottle or similar smooth-sided container, mesh or breathable covering, cordage, bait, small support sticks',
        construction: [
          "Choose a container large enough that the intended animal won't be cramped.",
          'Remove or modify the entrance so an animal can enter without cutting itself.',
          'Create a smooth funnel-like entrance.',
          'Place bait toward the rear.',
          'Secure the container so it cannot roll or tip.',
          'Provide ventilation.',
          'Test the entrance with a non-living object.',
          'Never use a container that could cause overheating, suffocation, or entanglement.',
        ],
        notes: [
          { label: 'Field consideration', text: 'Plastic containers can become dangerously hot in direct sunlight, so this type should not be left unattended.' },
        ],
      },
      {
        num: 22,
        name: 'Basket Funnel Trap',
        type: 'Live capture',
        difficulty: 2,
        materials: 'Flexible branches, stronger branches for a frame, cordage, bait',
        construction: [
          'Make a cylindrical or roughly rectangular basket.',
          'Weave flexible branches around the frame.',
          'Leave one opening.',
          'Construct a funnel from flexible material.',
          'Attach the wide end of the funnel to the basket.',
          'Make the inner opening large enough for the intended animal.',
          'Remove sharp branch ends.',
          'Put bait behind the funnel.',
          'Secure the basket so it cannot roll or collapse.',
        ],
        notes: [
          { label: 'Principle', text: 'The funnel creates a one-way-looking entrance without requiring a mechanical trigger.' },
        ],
      },
      {
        num: 23,
        name: 'Two-Entry Basket Trap',
        type: 'Live capture',
        difficulty: 3,
        intro: 'This is essentially a basket trap with entrances on opposite ends.',
        materials: 'Branches, cordage, bait, frame material',
        construction: [
          'Build a sturdy basket-shaped enclosure.',
          'Create a funnel entrance on one end.',
          'Create another on the opposite end.',
          'Keep both entrances smooth.',
          'Put bait in the center.',
          'Reinforce the basket with crosspieces.',
          'Test it for structural stability.',
          "Ensure the openings aren't capable of trapping limbs.",
        ],
        notes: [
          { label: 'Advantage', text: 'Useful where animal movement can approach the enclosure from either direction.' },
        ],
      },
      {
        num: 24,
        name: 'Wire-Mesh Cage Trap',
        type: 'Live capture',
        difficulty: 2,
        materials: 'Welded-wire or suitable mesh, frame material, hinges or sliding hardware, treadle, bait',
        construction: [
          'Construct a rectangular frame.',
          'Cover the sides and top with mesh.',
          'Fold or cover exposed wire ends.',
          'Install a freely moving entrance door.',
          'Add a treadle inside.',
          'Connect the treadle to the door mechanism.',
          'Put bait beyond the treadle.',
          'Test the door with a stick.',
          'Check that ventilation is adequate.',
          'Make sure the mesh size is appropriate for the intended animal.',
        ],
        notes: [
          { label: 'Advantage', text: 'More durable than most improvised natural-material traps.' },
        ],
      },
      {
        num: 25,
        name: 'Bucket Live Trap',
        type: 'Live-capture concept',
        difficulty: 2,
        intro: 'A bucket can be used as a simple enclosure only when it cannot cause injury.',
        materials: 'Large smooth-sided bucket/container, lightweight cover or lid, bait, optional ramp',
        construction: [
          'Select a container large enough for the intended animal.',
          "Make sure the inside surface doesn't contain sharp edges.",
          'Provide an appropriate entry route.',
          'Place bait inside.',
          'Secure the container so it cannot tip over.',
          'Provide ventilation.',
          "Don't use water or deep liquid as part of the setup.",
          "Don't leave an animal exposed to extreme heat or cold.",
        ],
        notes: [
          { label: 'Important', text: 'Never create a "fall trap" where an animal can fall far enough to break a leg or otherwise injure itself.' },
        ],
      },
      {
        num: 26,
        name: 'Tube Live Trap',
        type: 'Live capture',
        difficulty: 2,
        materials: 'Smooth-sided tube, end cap or cage, bait, trigger/door if appropriate',
        construction: [
          'Select a tube with enough internal diameter for the intended species.',
          'Remove sharp edges.',
          'Attach a secure end section.',
          'Create a door at the other end.',
          'Install a simple trigger if required.',
          'Put bait toward the closed end.',
          'Test the door mechanism.',
          'Ensure adequate ventilation.',
          'Never use a tube so narrow that an animal can become wedged.',
        ],
        notes: [
          { label: 'Best use', text: 'Learning how confined spaces can guide movement toward a capture chamber.' },
        ],
      },
      {
        num: 27,
        name: 'Funnel-Entry Cage Trap',
        type: 'Live capture',
        difficulty: 2,
        materials: 'Cage, mesh or flexible branches, cordage, bait',
        construction: [
          'Build a rectangular or cylindrical cage.',
          'Make a funnel from mesh or flexible material.',
          'Attach the funnel to the entrance.',
          'Make sure there are no exposed sharp wires.',
          'Position the bait inside the cage.',
          'Secure the trap against tipping.',
          'Test the entrance with a non-living object.',
          'Ensure an animal can move normally once inside.',
        ],
        notes: [
          { label: 'Difference from #22', text: 'This version uses a manufactured or rigid cage rather than relying entirely on woven natural material.' },
        ],
      },
      {
        num: 28,
        name: 'Double-Entry Cage Trap',
        type: 'Live capture',
        difficulty: 3,
        materials: 'Cage, two doors, treadle or trigger, bait',
        construction: [
          'Build a rectangular cage.',
          'Install doors at both ends.',
          'Ensure each door operates independently and safely.',
          'Place a treadle between the entrances.',
          'Connect the treadle to the doors.',
          'Put bait near the center.',
          'Test each entrance separately.',
          'Verify that neither door can injure an animal when closing.',
          'Secure the cage so it cannot be dragged or overturned.',
        ],
        notes: [
          { label: 'Useful principle', text: 'This design works particularly well as a demonstration of how a trap can accommodate movement from either direction.' },
        ],
      },
      {
        num: 29,
        name: 'Collapsible Field Cage',
        type: 'Portable live capture',
        difficulty: 3,
        materials: 'Lightweight mesh, flexible frame pieces, cordage, hinges or folding joints',
        construction: [
          'Construct four lightweight side frames.',
          'Join them at the corners with hinges or flexible cordage.',
          'Add a removable top.',
          'Build a simple entrance.',
          'Make sure the cage can fold flat.',
          'Reinforce the corners.',
          'Test it by assembling and collapsing it several times.',
          'Check that no gaps can trap paws, legs, or heads.',
        ],
        notes: [
          { label: 'Advantages', text: 'Lightweight. Portable. Reusable. Easier to transport than a rigid wooden trap.' },
        ],
      },
      {
        num: 30,
        name: 'Rock-and-Stick Enclosure',
        type: 'Primitive live-capture enclosure',
        difficulty: 2,
        materials: 'Rocks, sticks, brush, cordage if available',
        construction: [
          'Choose a stable location away from hazards.',
          'Arrange rocks and sticks into a low enclosure.',
          'Leave an obvious entrance.',
          'Gradually narrow the approach using branches.',
          'Keep the enclosure large enough for the intended animal.',
          'Remove sharp sticks from the interior.',
          'Use natural cover to make the structure less conspicuous.',
          'If bait is used, place it inside the enclosure.',
          'Do not create a structure that can collapse onto an animal.',
          'Dismantle it when no longer needed.',
        ],
        notes: [
          { label: 'Survival principle', text: 'This demonstrates funneling and confinement using materials immediately available in the environment, without relying on a complicated trigger.' },
        ],
      },
      {
        num: 31,
        name: 'Spring-Pole Capture Mechanism — Practice',
        type: 'Stored-energy mechanism',
        difficulty: 3,
        materials: 'Flexible sapling or pole, cordage, trigger stick, lightweight practice target',
        construction: [
          'Select a healthy, flexible pole that bends without cracking.',
          'Clear the area around it so nothing can be struck when it moves.',
          'Carefully bend the pole and determine its natural safe range.',
          'Attach a cordage line to the pole.',
          'Route the line toward a simple trigger.',
          'Use the trigger to hold the pole in its bent position.',
          'Place a lightweight dummy target in the movement area.',
          'Release the mechanism from the side, never from its path.',
          'Inspect the pole and cordage afterward for damage.',
        ],
        notes: [
          { label: 'Principle', text: 'A bent pole stores potential energy and releases it when the trigger is displaced.' },
          { label: 'Safety', text: 'Never stand in the travel path of a loaded spring pole.' },
        ],
      },
      {
        num: 32,
        name: 'Bent-Sapling Trigger',
        type: 'Primitive mechanical exercise',
        difficulty: 2,
        intro: 'This demonstrates how a naturally flexible branch can provide the force needed to operate a non-lethal training mechanism.',
        materials: 'Flexible branch, cordage, small wooden trigger, lightweight object',
        construction: [
          'Select a flexible branch.',
          'Bend it gently to determine its usable range.',
          'Tie a cord to the branch.',
          'Connect the other end to the training mechanism.',
          'Use a small stick as the trigger.',
          "Secure the system while keeping your body away from the branch's movement path.",
          'Test with a very light object.',
          'Adjust the trigger until release is predictable.',
          'Disassemble after practicing.',
        ],
        notes: [
          { label: 'Field lesson', text: 'Natural materials can act as springs, levers, and counterweights.' },
        ],
      },
      {
        num: 33,
        name: 'Tensioned-Branch Mechanism',
        type: 'Mechanical exercise',
        difficulty: 3,
        materials: 'Two branches, cordage, lightweight practice load, trigger stick',
        construction: [
          'Place one branch firmly against the ground or another stable object.',
          'Use the second flexible branch as the tension member.',
          'Bend the flexible branch carefully.',
          'Attach cordage to it.',
          'Route the cord through the training trigger.',
          "Make sure the trigger can release without your hands being near the tensioned branch.",
          'Test using a very light load.',
          'Increase complexity only after the basic mechanism works reliably.',
        ],
        notes: [
          { label: 'Failure points', text: 'Brittle wood. Rotten branches. Slipping knots. Excessive tension.' },
        ],
      },
      {
        num: 34,
        name: 'Toggle-Release Mechanism',
        type: 'Tension-release exercise',
        difficulty: 3,
        materials: 'Cordage, small wooden toggle, fixed support, lightweight practice load',
        construction: [
          'Tie one end of cordage to the practice load.',
          'Run the cord around a stable support.',
          'Place the toggle against the support.',
          'Arrange the toggle so it temporarily holds the tension.',
          'Attach a second piece of cordage to the toggle.',
          'Pull the second cord gently to rotate the toggle.',
          'Observe how a small rotational movement releases the larger load.',
          'Practice with increasingly sensitive trigger arrangements.',
        ],
        notes: [
          { label: 'Principle', text: 'A toggle converts a small rotational movement into a release of stored tension.' },
        ],
      },
      {
        num: 35,
        name: 'Running-Line Restraint — Training Model',
        type: 'Restraint-mechanism demonstration',
        difficulty: 3,
        intro: 'Because restraint snares can seriously injure animals and are regulated differently across jurisdictions, use this as a bench-top demonstration with a rigid dummy target.',
        materials: 'Cordage, wooden dowel, fixed anchor, dummy target',
        construction: [
          'Attach one end of cordage to a secure anchor.',
          'Form a sliding loop around the wooden dummy.',
          'Route the free end through the appropriate friction point.',
          'Pull the line slowly and observe how the loop changes size.',
          'Test the mechanism only on the dummy.',
          'Never place the loop around a person, pet, or live animal.',
          'Disassemble after demonstrating the mechanism.',
        ],
        notes: [
          { label: 'Principle', text: 'The loop converts linear tension into constriction around the target.' },
        ],
      },
      {
        num: 36,
        name: 'Spring-Loop Restraint — Demonstration',
        type: 'Mechanical demonstration',
        difficulty: 3,
        materials: 'Flexible training pole, cordage, wooden dummy, trigger stick',
        construction: [
          'Set the flexible pole in a stable training position.',
          'Attach cordage to the pole.',
          'Form a loose loop around the dummy.',
          'Route the line back toward the pole.',
          'Create a simple release mechanism.',
          'Test the system using only the dummy.',
          'Keep the loop completely slack during handling.',
          'Remove the system after testing.',
        ],
        notes: [
          { label: 'Important', text: "Don't adapt this demonstration into an unattended wildlife restraint without first determining that the specific device, target species, location, and season are legally permitted." },
        ],
      },
      {
        num: 37,
        name: 'Breakaway-Cable Demonstration',
        type: 'Safety-mechanism exercise',
        difficulty: 3,
        intro: 'This entry is actually useful for understanding why modern wildlife restraints sometimes incorporate breakaway components.',
        materials: 'Cable or strong cord, deliberately weak training connection, wooden dummy',
        construction: [
          'Connect the main line to the dummy.',
          'Insert a deliberately weak connection between the two.',
          'Apply gradually increasing force.',
          'Observe the point at which the weak connection separates.',
          'Replace the component and repeat the experiment.',
          'Record how different materials behave.',
        ],
        notes: [
          { label: 'Purpose', text: 'Demonstrates the concept of a predetermined failure point intended to reduce the risk of prolonged restraint of an unintended animal.' },
        ],
      },
      {
        num: 38,
        name: 'Pole-Assisted Cage Door',
        type: 'Live-capture mechanism',
        difficulty: 3,
        materials: 'Cage, lightweight door, flexible pole, cordage, treadle, suitable bait',
        construction: [
          'Build or obtain a suitable live-capture cage.',
          'Install a door that moves freely.',
          'Position the flexible pole outside the cage.',
          'Connect the pole to the door using cordage.',
          'Install a treadle inside the cage.',
          'Connect the treadle to the pole/door mechanism.',
          'Place bait beyond the treadle.',
          'Test the mechanism using a stick.',
          'Ensure the pole cannot strike or injure the captured animal.',
          'Make sure the door closes without crushing anything.',
        ],
        notes: [
          { label: 'Advantage', text: 'The spring mechanism can provide consistent door movement without requiring a heavy door.' },
        ],
      },
      {
        num: 39,
        name: 'Counterweight Cage Door',
        type: 'Live capture',
        difficulty: 3,
        materials: 'Cage, lightweight door, cordage, small counterweight, treadle',
        construction: [
          'Install a freely moving cage door.',
          'Attach a cord to the door.',
          'Route the cord over a smooth support.',
          'Attach the counterweight to the opposite end.',
          'Adjust the counterweight so it is just sufficient to move the door.',
          'Connect the treadle to the retaining mechanism.',
          'Place bait behind the treadle.',
          'Test the door repeatedly.',
          'Ensure the counterweight cannot fall onto the animal.',
        ],
        notes: [
          { label: 'Principle', text: 'Gravity supplies the force while the trigger determines when that force is released.' },
        ],
      },
      {
        num: 40,
        name: 'Resettable Live-Capture Trap',
        type: 'Live capture',
        difficulty: 3,
        materials: 'Rigid cage, door, treadle, cordage or mechanical linkage, bait',
        construction: [
          'Build a sturdy enclosure appropriate for the intended species.',
          'Install a freely moving door.',
          'Install the treadle near the rear.',
          'Connect the treadle to the door.',
          'Add a resettable retaining point.',
          'Place bait beyond the treadle.',
          'Test the complete mechanism several times.',
          'Confirm that the captured animal has adequate ventilation and room to move.',
          'Check for sharp edges, gaps, or pinch points.',
          'If legally deployed, inspect it at the interval required by the applicable wildlife regulations.',
        ],
        notes: [
          { label: 'Advantages', text: "Reusable. Doesn't require a falling weight. Can be reset quickly. Easier to inspect than many improvised mechanisms." },
        ],
      },
    ],
  },
  {
    key: 'fish',
    title: 'Fish Traps',
    emoji: '🐟',
    designs: [
      {
        num: 41,
        name: 'Bottle Fish Trap',
        type: 'Passive fish trap',
        difficulty: 2,
        materials: 'Large plastic bottle, knife or cutting tool, cordage, bait, small stones for ballast',
        construction: [
          'Choose a sturdy bottle with a wide enough body for the fish you are targeting.',
          'Cut off the upper portion near the shoulder.',
          'Turn the cut portion around so the mouth points inward.',
          'Secure the inverted section around the opening with cordage.',
          'Smooth or cover any sharp cut edges.',
          'Add a small amount of ballast so the trap stays in the desired position.',
          'Put suitable bait inside.',
          'Secure the trap so current cannot carry it away.',
          'Position it in suitable shallow water.',
          'Retrieve it frequently and release non-target animals immediately.',
        ],
        notes: [
          { label: 'Principle', text: 'Fish can enter through the funnel but have difficulty locating the entrance on their way back out.' },
          { label: 'Important', text: 'Bottle traps may be prohibited for some species or waters, so check local fishing regulations before deployment.' },
        ],
      },
      {
        num: 42,
        name: 'Funnel Fish Trap',
        type: 'Passive fish trap',
        difficulty: 2,
        materials: 'Wire mesh, plastic mesh, or suitable natural material, flexible sticks, cordage, bait, weights',
        construction: [
          'Make a cylindrical or rectangular frame.',
          'Cover the frame with mesh.',
          'Construct a funnel-shaped entrance.',
          'Attach the funnel securely to one end.',
          'Keep the entrance smooth and free of sharp projections.',
          'Place bait toward the rear.',
          'Add enough weight to keep the trap stable.',
          'Secure it against current.',
          'Position it where fish naturally travel.',
          'Check it frequently.',
        ],
        notes: [
          { label: 'Best locations', text: 'Edges of pools, slow-moving channels, and areas where fish naturally concentrate.' },
        ],
      },
      {
        num: 43,
        name: 'Basket Fish Trap',
        type: 'Primitive aquatic trap',
        difficulty: 3,
        materials: 'Flexible willow or similar branches, stronger branches, cordage, bait, stones for ballast',
        construction: [
          'Build a rigid circular or oval frame.',
          'Weave flexible branches around the frame.',
          'Leave an opening on one end.',
          'Weave a tapered funnel around the opening.',
          'Reinforce the frame with crosspieces.',
          'Remove sharp branch tips from the interior.',
          'Put bait inside.',
          "Add stones to prevent floating.",
          'Secure the trap in shallow water.',
          'Check it regularly.',
        ],
        notes: [
          { label: 'Advantage', text: "Can be constructed using natural materials when manufactured mesh isn't available." },
        ],
      },
      {
        num: 44,
        name: 'Woven-Stick Fish Trap',
        type: 'Primitive',
        difficulty: 4,
        intro: 'This is essentially a larger woven funnel enclosure.',
        materials: 'Straight sticks, flexible shoots, cordage, stones',
        construction: [
          'Drive or place several sturdy sticks to form a framework.',
          'Weave flexible branches horizontally around them.',
          'Leave one entrance.',
          'Build the entrance into a narrowing funnel.',
          'Reinforce the structure with additional vertical sticks.',
          'Make the interior free of sharp points.',
          'Anchor it with stones.',
          'Position it so water can flow through the structure.',
          "Don't completely block a natural watercourse.",
          'Check it frequently.',
        ],
        notes: [
          { label: 'Survival lesson', text: 'This teaches construction of large structures from flexible natural materials.' },
        ],
      },
      {
        num: 45,
        name: 'Rock-Weir Fish Trap',
        type: 'Passive fish-concentration structure',
        difficulty: 3,
        materials: 'Naturally occurring rocks, optional stakes/branches, bait if permitted/appropriate',
        construction: [
          'Identify a shallow section where fish naturally move.',
          'Arrange rocks into a partial barrier.',
          'Leave a deliberate opening.',
          'Shape the rocks so the opening funnels fish toward a small collection area.',
          'Keep water flowing freely.',
          'Avoid creating a complete blockage.',
          'Monitor the structure for shifting rocks.',
          'Remove it when finished.',
        ],
        notes: [
          { label: 'Principle', text: "A weir uses the fish's natural movement against flowing water to concentrate them in one location." },
          { label: 'Legal note', text: 'Weirs can have particularly strict regulations because they can interfere with fish passage.' },
        ],
      },
      {
        num: 46,
        name: 'V-Shaped Fish Weir',
        type: 'Fish-concentration structure',
        difficulty: 3,
        materials: 'Rocks or stakes, branches, cordage',
        construction: [
          'Choose shallow water with noticeable fish movement.',
          'Construct two short barriers.',
          'Angle them toward one another to form a broad V.',
          'Leave the point open or place a legal collection device there.',
          "Ensure the structure doesn't completely obstruct the waterway.",
          'Anchor loose branches.',
          'Check the structure frequently.',
        ],
        notes: [
          { label: 'Why the V shape works', text: 'The narrowing geometry concentrates movement toward the point.' },
        ],
      },
      {
        num: 47,
        name: 'Funnel Weir',
        type: 'Passive aquatic capture',
        difficulty: 3,
        intro: 'Best suited to: shallow streams and controlled-water environments where such devices are legal.',
        materials: 'Stakes, branches, cordage, mesh or basket material',
        construction: [
          'Establish two converging lines of stakes.',
          'Connect them with branches.',
          'Gradually narrow the passage.',
          'Place a legal collection basket or cage at the narrow end.',
          'Make sure water can continue flowing.',
          'Secure the collection device.',
          'Inspect the entire structure for gaps and hazards.',
          'Remove it when no longer needed.',
        ],
        notes: [],
      },
      {
        num: 48,
        name: 'Double-Funnel Fish Trap',
        type: 'Passive fish trap',
        difficulty: 3,
        materials: 'Mesh or woven material, frame sticks, cordage, bait',
        construction: [
          'Build a cylindrical or box-shaped enclosure.',
          'Install a funnel at each end.',
          'Make both funnels point inward.',
          'Put bait in the center.',
          'Reinforce the frame.',
          'Remove sharp material.',
          'Add ballast.',
          'Position the trap where fish can encounter either entrance.',
          'Secure it against current.',
          'Check it frequently.',
        ],
        notes: [
          { label: 'Advantage', text: 'Fish can enter from either direction.' },
        ],
      },
      {
        num: 49,
        name: 'Minnow Trap',
        type: 'Small-fish live trap',
        difficulty: 2,
        materials: 'Commercial minnow trap or suitable mesh container, bait, cordage, small weight',
        construction: [
          'Use a container with appropriately sized mesh.',
          'Make sure the funnel opening corresponds to the intended small fish.',
          'Place bait inside.',
          'Add a small weight.',
          'Tie the trap securely.',
          'Position it in shallow water or near cover.',
          'Keep part of the trap positioned so trapped animals have access to adequate water.',
          'Check it frequently.',
          'Release non-target species.',
          'Follow applicable baitfish/minnow regulations.',
        ],
        notes: [
          { label: 'Survival use', text: 'Small fish can potentially serve as food themselves or, where legal, as bait for larger fish.' },
        ],
      },
      {
        num: 50,
        name: 'Dip-Net Funnel Trap',
        type: 'Passive/active aquatic capture',
        difficulty: 2,
        materials: 'Dip net, flexible sticks, cordage, bait if appropriate',
        construction: [
          'Use a sturdy dip net with suitable mesh.',
          'Shape flexible sticks into a funnel or guide.',
          'Place the funnel in shallow water.',
          'Direct the opening toward the net.',
          'Position the net at the narrow end.',
          'Slowly disturb the surrounding water from behind the fish.',
          'Encourage fish toward the narrowing funnel.',
          'Lift the net smoothly once fish enter.',
          'Release unwanted species immediately.',
        ],
        notes: [
          { label: 'Advantage', text: "Unlike a passive trap, you can actively monitor what's being captured, reducing unintended catches." },
        ],
      },
      {
        num: 51,
        name: 'Eel-Style Funnel Trap',
        type: 'Passive aquatic trap',
        difficulty: 3,
        materials: 'Flexible sticks or suitable mesh, cordage, bait, small ballast stones',
        construction: [
          'Build a long, narrow cylindrical frame.',
          'Cover it with woven material or suitable mesh.',
          'Construct a tapered funnel entrance.',
          'Attach the funnel securely to the body.',
          'Place bait toward the closed end.',
          'Add ballast so the trap remains stable underwater.',
          'Secure it to the bank or another stable point.',
          'Position it in calm water near cover.',
          'Make sure the trap cannot become a hazard to other wildlife.',
          'Check it frequently.',
        ],
        notes: [
          { label: 'Principle', text: 'A long enclosure combined with a narrowing entrance encourages aquatic animals to continue moving inward.' },
        ],
      },
      {
        num: 52,
        name: 'Creek Basket Trap',
        type: 'Primitive fish trap',
        difficulty: 3,
        materials: 'Flexible branches, strong stakes, cordage, stones, bait where legal',
        construction: [
          'Select a shallow, slow-moving section of creek.',
          'Construct a basket-shaped frame.',
          'Weave flexible branches around the frame.',
          'Leave one opening facing the direction of expected fish movement.',
          'Shape the opening into a funnel.',
          'Reinforce the basket with crosspieces.',
          'Anchor it with stones.',
          'Tie it to a stable bank feature.',
          'Ensure water continues flowing around the trap.',
          'Check it frequently and remove it when finished.',
        ],
        notes: [
          { label: 'Field advantage', text: 'Most materials can be collected from the immediate environment.' },
        ],
      },
      {
        num: 53,
        name: 'Floating Bait Trap',
        type: 'Small aquatic live trap',
        difficulty: 2,
        materials: 'Floating container/cage, mesh, cordage, bait, small float',
        construction: [
          'Build or obtain a small mesh enclosure.',
          'Create an opening that allows the intended small aquatic animals to enter.',
          'Place bait inside.',
          'Attach the trap to a float.',
          'Tie the float to a secure anchor point.',
          'Position it at the desired depth.',
          'Make sure the enclosure remains partially submerged.',
          'Test its stability before leaving it.',
          'Check it frequently.',
          'Release unwanted catches.',
        ],
        notes: [
          { label: 'Important', text: "Don't use sealed containers that could deprive trapped animals of oxygen." },
        ],
      },
      {
        num: 54,
        name: 'Bank-Set Fish Trap',
        type: 'Passive aquatic trap',
        difficulty: 3,
        materials: 'Small cage or basket, cordage, stakes, bait',
        construction: [
          'Find a shallow area adjacent to a deeper pool.',
          'Identify a natural route between shallow and deeper water.',
          'Position the cage so its entrance faces the route.',
          'Secure the cage to stakes or another stable anchor.',
          'Put bait inside if permitted.',
          'Ensure the cage remains submerged as intended.',
          'Keep the entrance unobstructed.',
          'Test that the cage cannot roll or become buried.',
          'Check frequently.',
        ],
        notes: [
          { label: 'Principle', text: 'Natural underwater terrain can funnel fish toward a particular route.' },
        ],
      },
      {
        num: 55,
        name: 'Tidal Fish Weir',
        type: 'Intertidal fish-concentration structure',
        difficulty: 4,
        materials: 'Stakes, branches, rocks, cordage',
        construction: [
          'Select an appropriate shallow intertidal area.',
          'Observe the direction of tidal movement before constructing anything.',
          'Create a curved or angled barrier using stakes and branches.',
          'Leave openings rather than completely blocking the shoreline.',
          'Direct movement toward a designated collection area.',
          'Anchor the structure securely.',
          'Account for changing water levels.',
          'Never place yourself in a position where an incoming tide can cut off your escape.',
          'Check the structure during appropriate tidal conditions.',
          'Dismantle it afterward.',
        ],
        notes: [
          { label: 'Legal warning', text: 'Tidal weirs can be heavily regulated because they can intercept large numbers of fish and interfere with fish passage. Check local regulations before construction.' },
        ],
      },
    ],
  },
  {
    key: 'crayfish-crab',
    title: 'Crayfish & Crabs',
    emoji: '🦀',
    designs: [
      {
        num: 56,
        name: 'Bottle Crayfish Trap',
        type: 'Small aquatic live trap',
        difficulty: 2,
        materials: 'Large plastic bottle, cutting tool, cordage, bait, small ballast',
        construction: [
          'Select a sturdy bottle large enough for the intended crayfish.',
          'Cut off the upper section.',
          'Reverse the cut section so its opening points inward.',
          'Secure the section with cordage.',
          'Cover or smooth sharp plastic edges.',
          'Place bait inside.',
          'Add a small amount of ballast.',
          'Secure the trap near the bottom.',
          'Ensure water can freely enter and leave.',
          'Check it frequently.',
        ],
        notes: [
          { label: 'Tip', text: 'Positioning near submerged rocks, vegetation, or other crayfish cover can be more important than elaborate construction.' },
        ],
      },
      {
        num: 57,
        name: 'Funnel Crayfish Trap',
        type: 'Passive crayfish trap',
        difficulty: 2,
        materials: 'Mesh or woven material, flexible sticks, cordage, bait, weight',
        construction: [
          'Make a cylindrical or rectangular frame.',
          'Cover the frame with mesh.',
          'Construct a funnel entrance.',
          'Attach the funnel securely.',
          'Put bait in a protected location inside the trap.',
          'Add ballast.',
          'Secure the trap so current cannot move it.',
          'Place it near suitable bottom habitat.',
          'Keep the entrance unobstructed.',
          'Check it frequently.',
        ],
        notes: [
          { label: 'Best habitat', text: 'Rocky bottoms, submerged woody debris, and similar cover where crayfish naturally shelter.' },
        ],
      },
      {
        num: 58,
        name: 'Basket Crayfish Trap',
        type: 'Primitive trap',
        difficulty: 3,
        materials: 'Flexible branches, strong frame sticks, cordage, bait, stones',
        construction: [
          'Build a small cylindrical basket.',
          'Weave flexible branches around the frame.',
          'Create a funnel-shaped entrance.',
          'Reinforce the entrance with additional sticks.',
          'Remove sharp protrusions from the interior.',
          'Put bait toward the center.',
          'Add stones for ballast.',
          'Secure the trap against current.',
          'Position it near crayfish habitat.',
          'Inspect it regularly.',
        ],
        notes: [
          { label: 'Advantage', text: 'Can be constructed without manufactured mesh.' },
        ],
      },
      {
        num: 59,
        name: 'Two-Entry Crayfish Trap',
        type: 'Passive live capture',
        difficulty: 3,
        materials: 'Mesh/woven basket, two funnels, cordage, bait, weight',
        construction: [
          'Construct a sturdy central enclosure.',
          'Install a funnel at each end.',
          'Point both funnels inward.',
          'Place bait between the entrances.',
          'Reinforce the frame.',
          'Add ballast.',
          'Secure it to the bottom.',
          "Make sure the funnels aren't capable of injuring claws or legs.",
          'Check frequently.',
          'Release non-target animals.',
        ],
        notes: [
          { label: 'Advantage', text: 'Crayfish approaching from either direction can encounter an entrance.' },
        ],
      },
      {
        num: 60,
        name: 'Rock-Shelter Crayfish Trap',
        type: 'Primitive capture structure',
        difficulty: 2,
        materials: 'Rocks, short sticks, bait, optional cordage',
        construction: [
          'Locate suitable shallow crayfish habitat.',
          'Arrange several rocks to create a small artificial shelter.',
          'Leave an accessible opening.',
          'Put bait deeper inside the shelter.',
          'Make sure the rocks are stable and cannot collapse.',
          'Avoid creating a structure that can trap an animal underneath falling rocks.',
          'Observe the shelter periodically.',
          'Capture animals using an appropriate legal method rather than attempting to crush or pin them.',
        ],
        notes: [
          { label: 'Principle', text: 'Crayfish naturally seek dark, protected spaces, so habitat manipulation can sometimes be more useful than complicated mechanical traps.' },
        ],
      },
      {
        num: 61,
        name: 'Baited Crawfish Pot',
        type: 'Passive live capture',
        difficulty: 2,
        materials: "Commercial or homemade mesh container, funnel entrance, bait container or bait, cordage, weight",
        construction: [
          "Use a rigid mesh enclosure that won't collapse underwater.",
          'Install a funnel-shaped entrance.',
          'Put bait toward the center or rear.',
          "If loose bait is used, secure it so it isn't immediately washed away.",
          'Add enough weight to keep the trap on the bottom.',
          'Attach a retrieval line to the trap.',
          'Position it near rocky or vegetated bottom habitat.',
          'Keep the entrance unobstructed.',
          'Check it at the interval required by local regulations.',
          'Release undersized or non-target animals immediately.',
        ],
        notes: [
          { label: 'Field lesson', text: 'A durable trap with good placement is generally more useful than an elaborate trigger mechanism.' },
        ],
      },
      {
        num: 62,
        name: 'Crab Pot',
        type: 'Passive live capture',
        difficulty: 3,
        materials: 'Rigid mesh, frame material, funnel entrance, bait container, rope/cordage, appropriate weight',
        construction: [
          'Construct a rigid rectangular or cylindrical frame.',
          'Cover the frame with suitable mesh.',
          'Install one or more funnel entrances.',
          'Secure the funnel firmly to the frame.',
          'Install a bait container in the center.',
          'Add sufficient weight to prevent the trap from drifting.',
          'Attach an appropriate retrieval line.',
          'Check for sharp wire ends.',
          'Position the trap in suitable legal habitat.',
          'Retrieve and inspect it according to local regulations.',
        ],
        notes: [
          { label: 'Important', text: 'Marine trapping regulations can specify trap dimensions, escape openings, marking, buoy requirements, and soak times.' },
        ],
      },
      {
        num: 63,
        name: 'Funnel Crab Trap',
        type: 'Passive live capture',
        difficulty: 2,
        materials: 'Wire mesh, flexible or rigid frame, cordage, bait, weight',
        construction: [
          'Build a shallow cage.',
          'Create a funnel entrance from mesh.',
          'Point the narrow end toward the interior.',
          'Secure the funnel to the cage.',
          'Place bait beyond the funnel.',
          'Reinforce the cage corners.',
          'Remove exposed sharp wire.',
          'Add ballast.',
          'Secure the trap so waves or current cannot move it unpredictably.',
          'Check it regularly.',
        ],
        notes: [
          { label: 'Principle', text: 'The funnel creates a low-resistance entrance while the enclosed space provides a feeding area.' },
        ],
      },
      {
        num: 64,
        name: 'Shoreline Bait Trap',
        type: 'Small aquatic live capture',
        difficulty: 2,
        materials: 'Small mesh cage, bait, cordage, stakes',
        construction: [
          'Find a shallow shoreline area where the target species naturally moves.',
          'Place the cage so the entrance faces the water.',
          'Secure it with stakes.',
          'Put bait inside.',
          'Make sure the trap cannot be stranded by changing water levels.',
          'Ensure trapped animals have sufficient water and ventilation as appropriate.',
          'Check frequently.',
          'Remove non-target animals promptly.',
        ],
        notes: [
          { label: 'Best use', text: 'Areas with predictable shoreline movement rather than open, fast-moving water.' },
        ],
      },
      {
        num: 65,
        name: 'Aquatic Funnel Enclosure',
        type: 'Passive aquatic capture',
        difficulty: 3,
        materials: 'Stakes, branches, mesh or basket material, cordage',
        construction: [
          'Place two rows of stakes in shallow water.',
          'Angle the rows toward one another.',
          'Gradually narrow the passage.',
          'Place a removable collection cage at the narrow end.',
          'Leave enough room for water to flow.',
          'Secure loose branches.',
          'Make sure the structure cannot collapse.',
          'Check the collection area frequently.',
          'Release unwanted species.',
          'Completely dismantle the structure afterward.',
        ],
        notes: [
          { label: 'Principle', text: 'This combines a weir and funnel into one system.' },
        ],
      },
    ],
  },
  {
    key: 'bird-small-animal',
    title: 'Bird & Small-Animal Live Capture',
    emoji: '🐦',
    designs: [
      {
        num: 66,
        name: 'Basket Funnel Enclosure',
        type: 'Live capture',
        difficulty: 3,
        materials: 'Flexible branches, cordage, mesh or netting, bait where legally appropriate',
        construction: [
          'Construct a lightweight enclosure.',
          'Build a funnel-shaped entrance.',
          'Secure the funnel to the enclosure.',
          'Remove sharp branch ends.',
          'Place appropriate food inside.',
          'Keep the enclosure ventilated.',
          'Test the structure before use.',
          'Make sure captured animals cannot become entangled.',
          'Check frequently.',
          'Release non-target animals immediately.',
        ],
        notes: [
          { label: 'Important', text: 'Many wild birds are protected by federal and/or state law. A survival situation does not automatically make capturing them lawful.' },
        ],
      },
      {
        num: 67,
        name: 'Ground Funnel Trap',
        type: 'Live-capture enclosure',
        difficulty: 2,
        materials: 'Stakes, brush, mesh, cordage',
        construction: [
          'Choose an open, safe location.',
          'Create two lines of brush or stakes.',
          'Gradually bring the lines closer together.',
          'End the funnel at a live-capture cage.',
          'Leave the initial entrance broad.',
          "Avoid completely blocking an animal's normal travel route.",
          'Secure loose materials.',
          'Check the enclosure regularly.',
          'Remove the setup when finished.',
        ],
        notes: [
          { label: 'Principle', text: 'The funnel subtly directs movement without requiring a mechanical trigger.' },
        ],
      },
      {
        num: 68,
        name: 'Two-Entry Funnel Enclosure',
        type: 'Live capture',
        difficulty: 3,
        materials: 'Cage, two funnel entrances, cordage, bait',
        construction: [
          'Build a rigid enclosure.',
          'Install a funnel entrance at each end.',
          'Point both narrow openings toward the center.',
          'Put bait between the entrances.',
          'Reinforce the frame.',
          'Ensure the funnels have no sharp edges.',
          'Secure the enclosure against tipping.',
          'Test both entrances.',
          'Monitor it frequently if legally deployed.',
        ],
        notes: [
          { label: 'Advantage', text: 'Movement can enter from either direction.' },
        ],
      },
      {
        num: 69,
        name: 'Cage With Drop Door',
        type: 'Live capture',
        difficulty: 3,
        materials: 'Rigid cage, lightweight sliding/drop door, guide rails, treadle, cordage or mechanical linkage, bait',
        construction: [
          'Build a sturdy cage.',
          'Install two smooth guide rails around the entrance.',
          'Fit a lightweight door into the rails.',
          'Ensure the door can move freely.',
          'Install a treadle inside the cage.',
          "Connect the treadle to the door's retaining mechanism.",
          'Place bait beyond the treadle.',
          'Test the mechanism with a stick.',
          'Make sure the door closes without crushing or pinching.',
          'Check the trap according to applicable regulations.',
        ],
        notes: [
          { label: 'Key design requirement', text: 'The door should contain, not injure, the animal.' },
        ],
      },
      {
        num: 70,
        name: 'Trigger-Door Cage',
        type: 'Live capture',
        difficulty: 3,
        materials: 'Cage, hinged or sliding door, treadle, cordage, bait',
        construction: [
          'Build or obtain an appropriately sized cage.',
          'Install a freely moving entrance door.',
          'Position the treadle behind the entrance.',
          'Connect the treadle to the door using cordage or a mechanical linkage.',
          'Place bait beyond the treadle.',
          'Test the trigger using a stick.',
          'Adjust the trigger so it activates reliably without requiring excessive force.',
          'Cover or remove sharp edges.',
          'Verify that the captured animal has adequate ventilation and room to move.',
          'Inspect it at the legally required interval.',
        ],
        notes: [],
      },
      {
        num: 71,
        name: 'Elevated-Platform Cage Trap',
        type: 'Live-capture enclosure',
        difficulty: 2,
        materials: 'Rigid wire mesh or small cage, four short stakes, cordage, small platform or shelf, bait',
        construction: [
          'Build or use a rigid cage with a single entrance.',
          'Elevate the cage slightly above the ground on a stable platform.',
          'Secure the cage so it cannot tip or roll.',
          "Position the entrance toward the animal's expected approach.",
          'Put bait toward the rear of the enclosure.',
          'Use a simple mechanical door that closes without crushing or pinning the animal.',
        ],
        notes: [
          { label: 'Field lesson', text: 'Elevating a cage can reduce interference from ground debris and some non-target animals.' },
          { label: 'Important', text: "An elevated trap must be securely supported and checked frequently. Don't suspend an occupied animal where a fall could occur." },
        ],
      },
      {
        num: 72,
        name: 'Treadle Cage Trap',
        type: 'Live-capture',
        difficulty: 3,
        materials: 'Rigid cage, hinged door, flat treadle plate, cordage or mechanical linkage, bait',
        construction: [
          'Install the door so it can swing or slide closed.',
          'Place a flat treadle toward the back of the cage.',
          'Connect the treadle mechanically to the door-release mechanism.',
          'Put the bait beyond the treadle.',
          'Test the mechanism repeatedly with a lightweight dummy.',
          'Make sure the door closes without trapping body parts.',
        ],
        notes: [
          { label: 'Principle', text: "The animal's weight on the treadle activates the door." },
          { label: 'Field lesson', text: 'Treadles are useful for learning how mechanical triggers translate a small movement into a larger mechanical action.' },
        ],
      },
      {
        num: 73,
        name: 'Enclosure Funnel Trap',
        type: 'Passive live capture',
        difficulty: 2,
        materials: 'Branches, poles, or fencing, cordage, stakes, large enclosure, optional funnel-shaped entrance',
        construction: [
          'Construct a relatively large holding enclosure.',
          'Build two converging sides leading toward its entrance.',
          "Leave the narrow end wide enough that an animal isn't injured entering.",
          'Arrange the entrance so it guides rather than physically restrains the animal.',
          'Secure the enclosure against tipping or collapse.',
          'Place attractant inside when appropriate and legal.',
        ],
        notes: [
          { label: 'Principle', text: "Funnels exploit an animal's tendency to continue moving through an opening rather than reverse direction." },
          { label: 'Field lesson', text: 'This is essentially a primitive version of a corral or funnel enclosure.' },
        ],
      },
      {
        num: 74,
        name: 'Portable Funnel Enclosure',
        type: 'Reusable live-capture enclosure',
        difficulty: 2,
        materials: 'Lightweight fencing or mesh, stakes, hinges or cordage, carrying straps, optional cage section',
        construction: [
          'Make several lightweight fence panels.',
          'Connect them so they can fold for transport.',
          'Assemble them into a roughly circular or rectangular enclosure.',
          'Shape one portion into a funnel.',
          'Reinforce the corners with stakes.',
          'Add a removable cage or holding section if desired.',
        ],
        notes: [
          { label: 'Field lesson', text: 'Modular construction is much easier to transport than a permanent primitive trap.' },
        ],
      },
      {
        num: 75,
        name: 'Double-Funnel Enclosure',
        type: 'Passive live capture',
        difficulty: 3,
        materials: 'Mesh or woven fencing, stakes, cordage, two funnel sections, central holding enclosure',
        construction: [
          'Build a central holding enclosure.',
          'Attach a funnel entrance on two opposite sides.',
          'Make both funnels gradually narrow toward the enclosure.',
          'Secure the walls so an animal cannot simply push them aside.',
          'Keep the entrances large enough to prevent injury.',
          'Use the enclosure only where the target species and trapping method are lawful.',
        ],
        notes: [
          { label: 'Principle', text: 'Two entrances allow animals approaching from either direction to encounter the enclosure.' },
        ],
      },
      {
        num: 76,
        name: 'Portable Box Enclosure',
        type: 'Live-capture',
        difficulty: 2,
        materials: 'Plywood, plastic panels, or wire mesh, hinges, door, carry handle, ventilation openings',
        construction: [
          'Build a lightweight rectangular enclosure.',
          'Add ventilation on multiple sides.',
          'Install a secure door.',
          'Add a handle or carrying points.',
          'Round or cover sharp edges.',
          'Test the door repeatedly before field use.',
        ],
        notes: [
          { label: 'Field lesson', text: 'A good live-capture container prioritizes ventilation, structural strength, and easy animal removal over elaborate trigger mechanisms.' },
        ],
      },
      {
        num: 77,
        name: 'Sliding-Door Enclosure',
        type: 'Live capture',
        difficulty: 3,
        materials: 'Cage, sliding door panel, two guide rails, door stop, simple release mechanism',
        construction: [
          'Install two parallel guides at the entrance.',
          'Make the door slide freely between them.',
          'Add a stop so the door cannot fall completely out.',
          'Attach the release mechanism.',
          'Test the door with no animal present.',
          'Ensure the mechanism cannot guillotine or crush an animal.',
        ],
        notes: [
          { label: 'Principle', text: 'Gravity or a mechanical linkage moves the door vertically or horizontally.' },
          { label: 'Field lesson', text: 'Sliding doors are particularly useful for studying friction, alignment, and mechanical advantage.' },
        ],
      },
      {
        num: 78,
        name: 'Gravity-Door Cage',
        type: 'Live-capture',
        difficulty: 2,
        materials: 'Rigid cage, lightweight door, hinges or guides, retaining pin, cordage',
        construction: [
          'Build a rigid cage.',
          'Mount the door so gravity naturally moves it toward the closed position.',
          'Hold the door open with a simple retaining mechanism.',
          'Place the trigger or release mechanism inside the cage.',
          'Test the system with a non-living dummy.',
          'Ensure the door closes slowly enough to avoid striking an animal.',
        ],
        notes: [
          { label: 'Principle', text: 'Gravity supplies the closing force instead of a spring or bent branch.' },
        ],
      },
      {
        num: 79,
        name: 'Counterweight Cage Door — Pulley Variant',
        type: 'Mechanical live-capture',
        difficulty: 3,
        materials: 'Cage, hinged or sliding door, cordage, small counterweight, pulley or smooth guide, trigger mechanism',
        construction: [
          'Mount the cage door securely.',
          'Run cordage from the door to a small counterweight.',
          'Route the cord through a smooth guide or pulley.',
          'Use a simple release to hold the door open.',
          'Test with a very light dummy weight.',
          'Adjust the counterweight so the door moves reliably but gently.',
        ],
        notes: [
          { label: 'Principle', text: 'A counterweight converts gravitational force into controlled door movement.' },
          { label: 'Field lesson', text: 'This is a useful primitive-engineering exercise because it demonstrates leverage, pulley systems, and mechanical advantage.' },
        ],
      },
      {
        num: 80,
        name: 'Resettable Live-Capture Cage',
        type: 'Reusable live-capture system',
        difficulty: 3,
        materials: 'Rigid cage, door, treadle or trigger, cordage/linkage, bait holder, door-retaining mechanism',
        construction: [
          'Build a strong, reusable cage.',
          'Install a door that cannot injure an animal when closing.',
          'Connect the door to a resettable trigger.',
          'Position the trigger inside the cage.',
          'Put the bait beyond the trigger.',
          'Test the mechanism repeatedly using a non-living test object.',
          'Make sure the trap can be safely reset without placing fingers near moving parts.',
        ],
        notes: [
          { label: 'Field lesson', text: 'The important design feature is repeatability: the mechanism should be capable of being reset without rebuilding the entire device.' },
          { label: 'Important', text: 'Live traps should be species-appropriate, checked frequently, protected from temperature extremes, and used only where permitted. Wildlife trapping rules vary substantially by species, location, land ownership, and season.' },
        ],
      },
      {
        num: 81,
        name: 'Amphibian Funnel Trap',
        type: 'Passive live capture',
        difficulty: 2,
        materials: 'Plastic or wire-mesh container, funnel-shaped entrance, cordage, stakes, optional shelter material',
        construction: [
          "Use a smooth-sided container that won't injure an animal.",
          'Fit a funnel-shaped entrance into the opening.',
          'Make the entrance large enough for the intended species.',
          'Place the container where amphibians naturally travel, such as along a damp edge.',
          'Anchor it so it cannot roll or become submerged.',
          'Provide ventilation and protection from excessive heat.',
        ],
        notes: [
          { label: 'Principle', text: 'A funnel allows an animal to enter while making the exit less obvious.' },
          { label: 'Field lesson', text: 'Funnel geometry is one of the simplest recurring concepts in primitive trapping.' },
        ],
      },
      {
        num: 82,
        name: 'Reptile Funnel Enclosure',
        type: 'Live-capture enclosure',
        difficulty: 2,
        materials: 'Rigid container or cage, mesh funnel, stakes, cordage, shade material',
        construction: [
          'Construct a rigid enclosure with a funnel entrance.',
          'Eliminate sharp wire ends and exposed edges.',
          'Anchor the enclosure securely.',
          'Provide shade if it will be exposed to sunlight.',
          'Check the enclosure frequently.',
          'Release non-target animals promptly where legally required.',
        ],
        notes: [
          { label: 'Field lesson', text: 'Reptiles can be particularly vulnerable to overheating, so temperature management is as important as the capture mechanism.' },
        ],
      },
      {
        num: 83,
        name: 'Rock-and-Branch Funnel',
        type: 'Primitive enclosure',
        difficulty: 2,
        materials: 'Rocks, branches, flexible poles, cordage',
        construction: [
          'Arrange branches into two converging walls.',
          'Use rocks or stakes to keep the walls in place.',
          'Leave the narrow end open into a larger holding enclosure.',
          'Reinforce gaps where an animal could push through.',
          "Keep the enclosure large enough that an animal isn't compressed.",
          'Avoid unstable piles of heavy rocks.',
        ],
        notes: [
          { label: 'Principle', text: 'This uses the landscape itself as the structural material.' },
          { label: 'Field lesson', text: "Primitive trapping isn't necessarily about mechanisms — funneling animal movement can accomplish much of the work." },
        ],
      },
      {
        num: 84,
        name: 'Brush Funnel Enclosure',
        type: 'Primitive live capture',
        difficulty: 2,
        materials: 'Brush, fallen branches, stakes, cordage, existing natural barriers',
        construction: [
          'Identify a natural corridor such as a gap between vegetation.',
          'Extend the existing barriers with branches and brush.',
          'Shape the additions into a broad funnel.',
          'Direct the funnel toward a secure enclosure.',
          'Reinforce obvious escape gaps.',
          "Don't block established wildlife passages in ways that could cause dangerous crowding.",
        ],
        notes: [
          { label: 'Field lesson', text: 'Natural barriers can dramatically reduce the amount of material required.' },
        ],
      },
      {
        num: 85,
        name: 'Double-Entry Cage',
        type: 'Passive live capture',
        difficulty: 3,
        materials: 'Rigid cage, two funnel entrances, mesh or wire, stakes, optional bait holder',
        construction: [
          'Start with a rigid holding cage.',
          'Add a funnel entrance at each end.',
          'Make both entrances smooth and sufficiently large.',
          'Secure the cage so it cannot roll.',
          'Position it where animals may approach from either direction.',
          'Inspect both entrances regularly.',
        ],
        notes: [
          { label: 'Principle', text: 'Two entrances increase the number of directions from which an animal can enter.' },
        ],
      },
      {
        num: 86,
        name: 'Partitioned Holding Cage',
        type: 'Live-capture enclosure',
        difficulty: 3,
        materials: 'Large cage, removable mesh partition, door, stakes, cordage',
        construction: [
          'Construct a spacious cage.',
          'Add a removable internal partition.',
          'Make the partition secure but easy for the operator to remove.',
          'Keep adequate ventilation in every compartment.',
          'Use the partitions only to separate compatible, appropriately sized animals.',
          'Never overcrowd the enclosure.',
        ],
        notes: [
          { label: 'Field lesson', text: 'Modular cages allow one enclosure to serve several purposes without constructing an entirely new trap.' },
        ],
      },
      {
        num: 87,
        name: 'Funnel-to-Box Trap',
        type: 'Live capture',
        difficulty: 3,
        materials: 'Funnel, rigid box/cage, door, stakes, cordage',
        construction: [
          'Construct a funnel leading toward a rigid box.',
          'Make the transition between the funnel and box smooth.',
          'Secure the box to the ground.',
          'Use a non-crushing entrance mechanism.',
          'Test the complete system using a lightweight object.',
          'Make sure the operator can safely access and release the animal.',
        ],
        notes: [
          { label: 'Principle', text: 'The funnel concentrates movement into a controlled holding area.' },
        ],
      },
      {
        num: 88,
        name: 'Removable Funnel Trap',
        type: 'Reusable live-capture system',
        difficulty: 2,
        materials: 'Cage, removable funnel, clips or cordage, door, stakes',
        construction: [
          'Build a standard cage with a detachable entrance funnel.',
          'Secure the funnel with removable fasteners.',
          'Make the connection strong enough that an animal cannot dislodge it.',
          'Test the attachment before use.',
          'After capture, detach the funnel only when it is safe to do so.',
          'Store the components separately when transporting them.',
        ],
        notes: [
          { label: 'Field lesson', text: 'Detachable components make primitive equipment easier to transport, repair, and reconfigure.' },
        ],
      },
      {
        num: 89,
        name: 'Sliding-Partition Capture Cage',
        type: 'Live-capture / handling enclosure',
        difficulty: 3,
        materials: 'Large cage, sliding internal partition, guide rails, secure doors, smooth-sided panels',
        construction: [
          'Build a cage with an internal partition that can move along guides.',
          'Ensure the partition cannot fall or slam unexpectedly.',
          'Leave enough clearance to prevent pinching.',
          'Use the partition to divide the cage rather than physically restrain the animal.',
          'Test the movement with no animal present.',
          "Keep the operator's hands away from moving components.",
        ],
        notes: [
          { label: 'Principle', text: "Instead of trapping an animal with force, the enclosure itself controls its available space." },
          { label: 'Field lesson', text: 'This is closer to professional animal-handling equipment than a traditional primitive trap.' },
        ],
      },
      {
        num: 90,
        name: 'Observation/Release Cage',
        type: 'Humane holding and identification enclosure',
        difficulty: 2,
        materials: 'Wire mesh or rigid plastic cage, secure door, carry handle, shade cover, water container where appropriate',
        construction: [
          'Build a sturdy, ventilated enclosure.',
          'Install a secure door that cannot accidentally open during transport.',
          'Cover sharp edges and protruding wire.',
          'Add carrying handles away from the door mechanism.',
          'Provide shade when necessary.',
          'Design the door so the animal can be released without the handler reaching inside.',
        ],
        notes: [
          { label: 'Principle', text: 'The safest capture system is often one designed primarily around safe observation and release, rather than restraint.' },
          { label: 'Field lesson', text: 'In real wildlife work, species identification and minimizing handling stress are often more important than maximizing capture efficiency.' },
        ],
      },
      {
        num: 91,
        name: 'Multi-Entry Funnel Cage',
        type: 'Passive live capture',
        difficulty: 3,
        materials: 'Rigid cage, several funnel entrances, wire mesh or rigid panels, stakes, cordage',
        construction: [
          'Start with a sturdy holding cage.',
          'Install funnel entrances on two or more sides.',
          'Make each entrance smooth and sufficiently wide for the intended species.',
          'Secure the cage so it cannot roll or collapse.',
          'Inspect every entrance regularly.',
          'Keep the interior free of sharp projections.',
        ],
        notes: [
          { label: 'Principle', text: 'Multiple entrances allow the enclosure to intercept movement from several directions.' },
          { label: 'Field lesson', text: 'Increasing the number of entrances can be more effective than making one entrance mechanically complicated.' },
        ],
      },
      {
        num: 92,
        name: 'Corner-Funnel Enclosure',
        type: 'Passive enclosure',
        difficulty: 2,
        materials: 'Branches or lightweight fencing, stakes, cordage, existing natural barriers',
        construction: [
          'Select a natural corner formed by vegetation, rocks, or terrain.',
          'Extend two barriers from the corner.',
          'Angle them inward toward an enclosed holding area.',
          'Secure the barriers with stakes.',
          'Eliminate dangerous gaps without creating sharp projections.',
          'Keep the enclosure stable and spacious.',
        ],
        notes: [
          { label: 'Principle', text: 'Animals encountering converging barriers tend to follow the available path toward the opening.' },
          { label: 'Field lesson', text: 'Terrain can substitute for much of the structure normally required for a trap.' },
        ],
      },
      {
        num: 93,
        name: 'Portable Three-Panel Enclosure',
        type: 'Reusable live-capture enclosure',
        difficulty: 2,
        materials: 'Three rigid mesh panels, hinges or cordage, stakes, door panel',
        construction: [
          'Make three lightweight rectangular panels.',
          'Connect them so they fold together for transport.',
          'Assemble them into a triangular or three-sided enclosure.',
          'Add a removable door or fourth panel.',
          'Stake the enclosure securely when deployed.',
          'Cover sharp corners and wire ends.',
        ],
        notes: [
          { label: 'Field lesson', text: 'A small number of modular panels can create several different enclosure shapes.' },
        ],
      },
      {
        num: 94,
        name: 'Four-Panel Foldable Cage',
        type: 'Reusable live capture',
        difficulty: 3,
        materials: 'Four mesh panels, hinges or cordage, door, stakes, carrying handle',
        construction: [
          'Connect four panels edge-to-edge.',
          'Make the joints fold inward.',
          'Add a separate secure door.',
          'Install carrying points on the frame.',
          'Deploy the panels into a rectangular cage.',
          'Stake the cage when necessary.',
        ],
        notes: [
          { label: 'Principle', text: 'Folding construction dramatically reduces the volume of equipment during transport.' },
        ],
      },
      {
        num: 95,
        name: 'Removable-Partition Fish Holding Trap',
        type: 'Aquatic holding/collection device',
        difficulty: 3,
        materials: 'Rigid aquatic-safe container, mesh partition, funnel entrance, retrieval line, floats or anchor',
        construction: [
          'Build a ventilated aquatic enclosure.',
          'Add a removable internal partition.',
          'Install a funnel entrance.',
          'Attach a retrieval line.',
          'Keep the enclosure positioned so it cannot become dangerously submerged or trapped.',
          'Make the partition removable without reaching into an occupied compartment.',
        ],
        notes: [
          { label: 'Field lesson', text: 'Separating the capture area from the handling area can make examination and release safer.' },
          { label: 'Important', text: 'Fish and aquatic organisms are subject to species, season, size, gear, and location restrictions.' },
        ],
      },
      {
        num: 96,
        name: 'Floating Observation Cage',
        type: 'Aquatic live holding',
        difficulty: 2,
        materials: 'Mesh cage, flotation material, retrieval line, secure frame, weights/anchor',
        construction: [
          'Construct a mesh enclosure that permits continuous water exchange.',
          'Attach flotation so the cage remains at the intended depth.',
          'Attach a retrieval line.',
          'Add a small anchor or weight if necessary.',
          'Test flotation before placing anything inside.',
          'Ensure the cage cannot become a navigation hazard.',
        ],
        notes: [
          { label: 'Principle', text: 'Buoyancy can keep a collection enclosure in a predictable position while allowing water to circulate.' },
        ],
      },
      {
        num: 97,
        name: 'Bait-Station Observation Cage',
        type: 'Non-lethal observation device',
        difficulty: 2,
        materials: 'Rigid cage, bait holder, observation opening, door, stakes',
        construction: [
          'Build a cage large enough for temporary observation.',
          'Place the bait holder toward the rear.',
          'Keep the bait holder separate from the door mechanism.',
          'Provide an observation opening or transparent panel.',
          'Secure the cage against movement.',
          'Design the door for rapid release.',
        ],
        notes: [
          { label: 'Field lesson', text: "A device doesn't have to capture an animal to be useful — observation and identification can be the objective." },
        ],
      },
      {
        num: 98,
        name: 'Mechanical Trigger Training Board',
        type: 'Practice/educational mechanism',
        difficulty: 2,
        materials: 'Wooden board, dowels or sticks, cordage, small lightweight object, pegs',
        construction: [
          'Mount several pegs or dowels onto a board.',
          'Create a simple release mechanism using cordage.',
          'Attach only a very light training object.',
          'Experiment with different trigger geometries.',
          'Measure how changes in angle affect release.',
          'Keep fingers away from moving components.',
        ],
        notes: [
          { label: 'Principle', text: "This isolates the mechanics of triggers without involving an animal." },
          { label: 'Field lesson', text: 'Learning trigger geometry on a bench is considerably safer than experimenting with a live animal.' },
        ],
      },
      {
        num: 99,
        name: 'Universal Primitive Cage Frame',
        type: 'Modular enclosure',
        difficulty: 3,
        materials: 'Straight poles, cordage, mesh, stakes, hinges or lashings',
        construction: [
          'Build a rectangular pole framework.',
          'Lash the corners securely.',
          'Cover the framework with appropriate mesh.',
          'Add a removable door frame.',
          'Add attachment points for interchangeable funnel entrances.',
          'Test the entire structure for stability.',
        ],
        notes: [
          { label: 'Principle', text: 'A standardized frame can accept different doors, funnels, partitions, and covers.' },
          { label: 'Field lesson', text: 'This demonstrates an important survival-design principle: build one adaptable system rather than many specialized pieces of equipment.' },
        ],
      },
      {
        num: 100,
        name: 'Modular Live-Capture System',
        type: 'Reconfigurable enclosure system',
        difficulty: 4,
        materials: 'Several mesh panels, interchangeable funnel sections, doors, stakes, cordage, removable partitions, retrieval/transport handles',
        construction: [
          'Build several standardized cage panels.',
          'Make the panels connect using compatible attachment points.',
          'Construct interchangeable funnel entrances.',
          'Build at least one secure door.',
          'Add removable internal partitions.',
          'Design the system so it can be assembled as a small cage, larger enclosure, or funnel arrangement.',
          'Test every configuration without an animal present.',
          'Inspect all edges, joints, doors, and attachment points before use.',
        ],
        notes: [
          { label: 'Principle', text: 'The system combines the major concepts covered throughout the 100 designs: funnels, cages, doors, partitions, modular construction, and safe handling.' },
          { label: 'Field lesson', text: 'The most useful survival equipment is often equipment that can perform multiple jobs rather than a collection of single-purpose devices.' },
        ],
      },
    ],
  },
]

export const TRAP_DESIGN_COUNT = TRAP_CATEGORIES.reduce((total, category) => total + category.designs.length, 0)
